collections:
  - name: elreydetoda.virtualization
  - name: amazon.aws
    version: 2.0.0
  # - name: community.general
  #   version: 4.0.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.docker
    version: 2.0.0
roles:
  - name: elreydetoda.gh_dl
